[".zi/bin"]
type = "git-repo"
url = "https://github.com/z-shell/zi.git"
refreshPeriod = "168h"
[".zi/bin".pull]
args = ["--ff-only"]

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"
[".tmux/plugins/tpm".pull]
args = ["--ff-only"]

[".config/vim/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"
