[".zi/bin"]
type = "archive"
url = "https://github.com/z-shell/zi/archive/master.tar.gz"
exact = true
stripComponents = 1

[".tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
exact = true
stripComponents = 1
