#!/usr/bin/env bash

cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
    # install homebrew if it's missing
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    brew bundle --file="$HOME/.yadm/Brewfile"

    if [ -d "$HOME/.iterm2" ]; then
        echo "Setting iTerm preference folder"
        defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
    fi
fi


if command -v vim >/dev/null 2>&1; then
    echo "Bootstraping Vim"
    if empty(glob("~/.vim/autoload/plug.vim"))
        silent! execute '!curl --create-dirs -fsSLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim'
    fi
    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
